using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

public class MenuManager : MonoBehaviour
{
 

    
    // Start is called before the first frame update



    void Start()
    {

        Cursor.visible = true;
        Cursor.lockState = CursorLockMode.None;




    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public void PlayGame()
    {

        SceneManager.LoadScene(1);


    }


    public void PlayAgain()
    {

        SceneManager.LoadScene(0);


    }


    public void Win()
    {

        SceneManager.LoadScene(0);



    }



}
